services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27018:27017"
    
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: